### ISSUE TITLE
docker bug

### ISSUE THREAD

**Issue by thelege2nd** [stackblitz-labs/bolt.diy#1203]
### Describe the bug

Issue with .env Changes:
I noticed that when making changes to the .env file, the Docker container detects those changes and restarts itself automatically. However, it doesn’t actually apply the updated environment variables unless the project is rebuilt. To resolve this, I manually rebuilt the containers whenever I updated the .env file:
Default docker-compose.yml Configuration:
The default docker-compose.yml file was configured to use env_file: ".env.local". Since the repository doesn’t include a .env.local file and only provides a .env file, I updated it to reference .env instead:
Explicit Network Declaration:
I added a custom network to better organize the services. This wasn’t strictly necessary, but it helped ensure all containers are on the same network for consistency:
networks:
  default:
    name: bolt-network
    driver: bridge
Environment Variables for Local Server:

Lastly, I updated the .env file to include the correct configuration for accessing my local server:
OPENAI_LIKE_API_BASE_URL=http://host.docker.internal:15432
Now it works finally. But since i did not use the app yet, its giving me this terminal error, is this an expected behavior or is there something wrong again with my installation?

### Link to the Bolt URL that caused the error

no URL

### Steps to reproduce

Change Default docker-compose.yml Configuration to use env_file: ".env  instead of env.local

2. http://host.docker.internal:15432 seems to be the only endpoint working for for openAILIKE API.

### Expected behavior

all good now.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by leex279** [comment]
Hi, are you on the latest main branch changes? there was this PR which should fix it: https://github.com/stackblitz-labs/bolt.diy/pull/1170

coming next stable release then to stable.

**Comment by thelege2nd** [comment]
Yes, I use the latest main branch. it wasn't fixed for me. Should I use stable or main?

**Comment by leex279** [comment]
Main is fine. just to make sure => you were not on the latest main before and had docker already running. then you updatet (git pull) and switched to main.
After this you also rebuild your containers and not just start them up?

**Comment by thelege2nd** [comment]
Yea i noticed, thanks.
