### ISSUE TITLE
Error while building with docker

### ISSUE THREAD

**Issue by AkremGomri** [stackblitz-labs/bolt.diy#1996]
### Describe the bug

So, a week ago I was able to build the project with docker. Today, I had the project deleted and repeated the installation and build process of that of the past week. But, when I execute :
`npm run dockerbuild`
or
`docker build . --target bolt-ai-development`

It fails and raises the following error :
`ERROR: failed to build: failed to solve: target stage "bolt-ai-development" could not be found`

I investigated in your Dockerfile (in github), and it turned out that you have deleted the named build stage of bolt-ai-development when comparing your commits f9f5574 and its previous c64f69b.
The newer commit f9f5574 no longer contain the bolt-ai-development named build stage.

  

### Link to the Bolt URL that caused the error

https://github.com/stackblitz-labs/bolt.diy

### Steps to reproduce

1. Clone the project :  
    - Go to [bolt.diy](https://github.com/stackblitz-labs/bolt.diy)
    - Run `git clone https://github.com/stackblitz-labs/bolt.diy.git`
    - Run `cd bolt.diy`
2. Set up env variables:
    - Run `nano .env.example`
    - Set the env variables
    - Run `./scripts/setup-env.sh`
2. Build the Docker Image (Assuming you have docker, npm, and Node installed):
    - Using npm script: `npm run dockerbuild`

   - OR using direct Docker command: `docker build . --target bolt-ai-development`

### Expected behavior

It is expected to get built so that I can move on to running the container !
But obviously bolt-ai-development does not exist in the Dockerfile, which causes inconsistencies with the documentation installation guide.

### Screen Recording / Screenshot

<img width="946" height="748" alt="Image" src="https://github.com/user-attachments/assets/b7629564-1f25-4caf-832f-a8bfe95790fd" />

### Platform

- OS: Ubuntu
- Version: 22.04.5 LTS

**Comment by Stijnus** [comment]
Hi,

Will fix it asap in a new PR.

Br,

Stijnus

**Comment by Stijnus** [comment]
This is fixed and will close the issue

**Comment by RudiBott** [comment]
Hello, i have the same issue. Just downloaded the latest build from here.

**Comment by jmyching** [comment]
Still having this issue today:

docker compose --profile development up --build -d
[+] Building 0.2s (2/2) FINISHED                                                                                                                                                                                                                                        
 => [internal] load local bake definitions                                                                                                                                                                                                                         0.0s
 => => reading from stdin 544B                                                                                                                                                                                                                                     0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                               0.0s
 => => transferring dockerfile: 2.52kB                                                                                                                                                                                                                             0.0s
failed to solve: target stage "bolt-ai-development" could not be found

Quick fix:

Edit docker-compose.yaml and replace:

target: bolt-ai-development

with:

target: development

**Comment by AkremGomri** [comment]
I am still having the same issue when trying to install it with docker.

**Comment by AkremGomri** [comment]
@jmyching I still get another error when I apply the fix you suggested. Here is the error:

<img width="738" height="532" alt="Image" src="https://github.com/user-attachments/assets/a7d0164d-45e3-48e1-8d5c-88bb5ffedf9f" />

**Comment by mouradamri21** [comment]
> [@jmyching](https://github.com/jmyching) I still get another error when I apply the fix you suggested. Here is the error:
> 
> <img alt="Image" width="738" height="532" src="https://private-user-images.githubusercontent.com/77440987/497540692-a7d0164d-45e3-48e1-8d5c-88bb5ffedf9f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTk3NjQxODYsIm5iZiI6MTc1OTc2Mzg4NiwicGF0aCI6Ii83NzQ0MDk4Ny80OTc1NDA2OTItYTdkMDE2NGQtNDVlMy00OGUxLThkNWMtODhiYjVmZmVkZjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDA2VDE1MTgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZWM0NmUyMDdhY2ZhNjIxMTJkNGIxNTg0NmZjMTZhOGFkZTIzOTUwNmIxOGI1ZDRjODI3MGM3YzFjYjMzMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z6F48z-2ZNMqL1mxk-sv5s0rlKSi5FcEQ9LY7hk5yBA">

I fixed that with this quick fix:
in docker-composer.yaml file at line 77 edit this:

`command: pnpm run dev --host 0.0.0.0`
to
`command: sh -c "pnpm install && pnpm run dev --host 0.0.0.0"`

**Comment by AkremGomri** [comment]
You solved it !
Thank you.
